In [2]:
import pymysql
import csv

In [3]:
FILE_CSV = 'iris.data'

In [4]:
import pandas as pd

In [5]:
pd.read_csv(FILE_CSV)

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [12]:
db_conn = pymysql.connect(host="139.162.170.240", 
                          user='nordic', 
                          passwd='password0', 
                          db='nordicDB')

cursor = db_conn.cursor()

In [7]:
query = """
    CREATE TABLE IF NOT EXISTS main_table_d (
        ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
        sepal_length_in_cm FLOAT NOT NULL,
        sepal_width_in_cm FLOAT NOT NULL,
        petal_length_in_cm FLOAT NOT NULL,
        petal_width_in_cm FLOAT,
        class_name TEXT NOT NULL

    )
"""

cursor.execute(query)
db_conn.commit()

In [10]:
query = """
    INSERT INTO main_table_d (
        
        `sepal_length_in_cm`,
        `sepal_width_in_cm`,
        `petal_length_in_cm`,
        `petal_width_in_cm`,
        `class_name`
    )
    VALUES (%s, %s, %s, %s, %s)
"""



In [13]:
with open(FILE_CSV) as f:
    f_read = csv.reader(f)
    for row in f_read:
        print(row)
        if len(row) > 0:
            cursor.execute(query, row)

db_conn.commit()

['5.1', '3.5', '1.4', '0.2', 'Iris-setosa']
['4.9', '3.0', '1.4', '0.2', 'Iris-setosa']
['4.7', '3.2', '1.3', '0.2', 'Iris-setosa']
['4.6', '3.1', '1.5', '0.2', 'Iris-setosa']
['5.0', '3.6', '1.4', '0.2', 'Iris-setosa']
['5.4', '3.9', '1.7', '0.4', 'Iris-setosa']
['4.6', '3.4', '1.4', '0.3', 'Iris-setosa']
['5.0', '3.4', '1.5', '0.2', 'Iris-setosa']
['4.4', '2.9', '1.4', '0.2', 'Iris-setosa']
['4.9', '3.1', '1.5', '0.1', 'Iris-setosa']
['5.4', '3.7', '1.5', '0.2', 'Iris-setosa']
['4.8', '3.4', '1.6', '0.2', 'Iris-setosa']
['4.8', '3.0', '1.4', '0.1', 'Iris-setosa']
['4.3', '3.0', '1.1', '0.1', 'Iris-setosa']
['5.8', '4.0', '1.2', '0.2', 'Iris-setosa']
['5.7', '4.4', '1.5', '0.4', 'Iris-setosa']
['5.4', '3.9', '1.3', '0.4', 'Iris-setosa']
['5.1', '3.5', '1.4', '0.3', 'Iris-setosa']
['5.7', '3.8', '1.7', '0.3', 'Iris-setosa']
['5.1', '3.8', '1.5', '0.3', 'Iris-setosa']
['5.4', '3.4', '1.7', '0.2', 'Iris-setosa']
['5.1', '3.7', '1.5', '0.4', 'Iris-setosa']
['4.6', '3.6', '1.0', '0.2', 'Ir

In [14]:
query_select_all = """
SELECT *
from main_table_d
"""

cursor.execute(query_select_all)
cursor.fetchall()

((1, 5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
 (2, 4.9, 3.0, 1.4, 0.2, 'Iris-setosa'),
 (3, 4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
 (4, 4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
 (5, 5.0, 3.6, 1.4, 0.2, 'Iris-setosa'),
 (6, 5.4, 3.9, 1.7, 0.4, 'Iris-setosa'),
 (7, 4.6, 3.4, 1.4, 0.3, 'Iris-setosa'),
 (8, 5.0, 3.4, 1.5, 0.2, 'Iris-setosa'),
 (9, 4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
 (10, 4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
 (11, 5.4, 3.7, 1.5, 0.2, 'Iris-setosa'),
 (12, 4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
 (13, 4.8, 3.0, 1.4, 0.1, 'Iris-setosa'),
 (14, 4.3, 3.0, 1.1, 0.1, 'Iris-setosa'),
 (15, 5.8, 4.0, 1.2, 0.2, 'Iris-setosa'),
 (16, 5.7, 4.4, 1.5, 0.4, 'Iris-setosa'),
 (17, 5.4, 3.9, 1.3, 0.4, 'Iris-setosa'),
 (18, 5.1, 3.5, 1.4, 0.3, 'Iris-setosa'),
 (19, 5.7, 3.8, 1.7, 0.3, 'Iris-setosa'),
 (20, 5.1, 3.8, 1.5, 0.3, 'Iris-setosa'),
 (21, 5.4, 3.4, 1.7, 0.2, 'Iris-setosa'),
 (22, 5.1, 3.7, 1.5, 0.4, 'Iris-setosa'),
 (23, 4.6, 3.6, 1.0, 0.2, 'Iris-setosa'),
 (24, 5.1, 3.3, 1.7, 0.5, 'Iris-setosa'),
 

In [17]:
query = """
    SELECT count(ID)
    from main_table_d
"""

cursor.execute(query)
cursor.fetchall()[0][0]

150

In [19]:
query = """
    SELECT avg(sepal_length_in_cm)
    from main_table_d
"""
cursor.execute(query)
cursor.fetchall()[0][0]

5.843333326975505

In [20]:
query = """
    SELECT sum(sepal_length_in_cm)
    from main_table_d
"""
cursor.execute(query)
cursor.fetchall()[0][0]

876.4999990463257

In [21]:
query = """
    SELECT min(id)
    from main_table_d
"""
cursor.execute(query)
cursor.fetchall()[0][0]

1

In [25]:
query = """
    SELECT distinct class_name
    from main_table_d
"""
cursor.execute(query)
#cursor.fetchall()
list(map(lambda x: x[0], cursor.fetchall()))

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

In [ ]:
lambda x: x[0]

это то же самое, что

def f(x):
    return x[0]

In [26]:
query = """
    SELECT distinct sepal_length_in_cm, class_name
    from main_table_d
"""
cursor.execute(query)
cursor.fetchall()

((5.1, 'Iris-setosa'),
 (4.9, 'Iris-setosa'),
 (4.7, 'Iris-setosa'),
 (4.6, 'Iris-setosa'),
 (5.0, 'Iris-setosa'),
 (5.4, 'Iris-setosa'),
 (4.4, 'Iris-setosa'),
 (4.8, 'Iris-setosa'),
 (4.3, 'Iris-setosa'),
 (5.8, 'Iris-setosa'),
 (5.7, 'Iris-setosa'),
 (5.2, 'Iris-setosa'),
 (5.5, 'Iris-setosa'),
 (4.5, 'Iris-setosa'),
 (5.3, 'Iris-setosa'),
 (7.0, 'Iris-versicolor'),
 (6.4, 'Iris-versicolor'),
 (6.9, 'Iris-versicolor'),
 (5.5, 'Iris-versicolor'),
 (6.5, 'Iris-versicolor'),
 (5.7, 'Iris-versicolor'),
 (6.3, 'Iris-versicolor'),
 (4.9, 'Iris-versicolor'),
 (6.6, 'Iris-versicolor'),
 (5.2, 'Iris-versicolor'),
 (5.0, 'Iris-versicolor'),
 (5.9, 'Iris-versicolor'),
 (6.0, 'Iris-versicolor'),
 (6.1, 'Iris-versicolor'),
 (5.6, 'Iris-versicolor'),
 (6.7, 'Iris-versicolor'),
 (5.8, 'Iris-versicolor'),
 (6.2, 'Iris-versicolor'),
 (6.8, 'Iris-versicolor'),
 (5.4, 'Iris-versicolor'),
 (5.1, 'Iris-versicolor'),
 (6.3, 'Iris-virginica'),
 (5.8, 'Iris-virginica'),
 (7.1, 'Iris-virginica'),
 (6.5, 'Ir

In [27]:
query = """
    SELECT count(distinct class_name)
    from main_table_d
"""
cursor.execute(query)
cursor.fetchall()

((3,),)

In [ ]:
query = """
    SELECT count(*)
    from (
    select distinct class_name)
    from main_table_d
"""
cursor.execute(query)
cursor.fetchall()

In [29]:
query = """
    SELECT *
    from main_table_d
    where class_name = 'Iris-versicolor'
"""
cursor.execute(query)
cursor.fetchall()

((51, 7.0, 3.2, 4.7, 1.4, 'Iris-versicolor'),
 (52, 6.4, 3.2, 4.5, 1.5, 'Iris-versicolor'),
 (53, 6.9, 3.1, 4.9, 1.5, 'Iris-versicolor'),
 (54, 5.5, 2.3, 4.0, 1.3, 'Iris-versicolor'),
 (55, 6.5, 2.8, 4.6, 1.5, 'Iris-versicolor'),
 (56, 5.7, 2.8, 4.5, 1.3, 'Iris-versicolor'),
 (57, 6.3, 3.3, 4.7, 1.6, 'Iris-versicolor'),
 (58, 4.9, 2.4, 3.3, 1.0, 'Iris-versicolor'),
 (59, 6.6, 2.9, 4.6, 1.3, 'Iris-versicolor'),
 (60, 5.2, 2.7, 3.9, 1.4, 'Iris-versicolor'),
 (61, 5.0, 2.0, 3.5, 1.0, 'Iris-versicolor'),
 (62, 5.9, 3.0, 4.2, 1.5, 'Iris-versicolor'),
 (63, 6.0, 2.2, 4.0, 1.0, 'Iris-versicolor'),
 (64, 6.1, 2.9, 4.7, 1.4, 'Iris-versicolor'),
 (65, 5.6, 2.9, 3.6, 1.3, 'Iris-versicolor'),
 (66, 6.7, 3.1, 4.4, 1.4, 'Iris-versicolor'),
 (67, 5.6, 3.0, 4.5, 1.5, 'Iris-versicolor'),
 (68, 5.8, 2.7, 4.1, 1.0, 'Iris-versicolor'),
 (69, 6.2, 2.2, 4.5, 1.5, 'Iris-versicolor'),
 (70, 5.6, 2.5, 3.9, 1.1, 'Iris-versicolor'),
 (71, 5.9, 3.2, 4.8, 1.8, 'Iris-versicolor'),
 (72, 6.1, 2.8, 4.0, 1.3, 'Iris-ve

In [30]:
query = """
    SELECT *
    from main_table_d
        where class_name = 'Iris-versicolor'
        and 
        sepal_length_in_cm < 6
"""
cursor.execute(query)
cursor.fetchall()

((54, 5.5, 2.3, 4.0, 1.3, 'Iris-versicolor'),
 (56, 5.7, 2.8, 4.5, 1.3, 'Iris-versicolor'),
 (58, 4.9, 2.4, 3.3, 1.0, 'Iris-versicolor'),
 (60, 5.2, 2.7, 3.9, 1.4, 'Iris-versicolor'),
 (61, 5.0, 2.0, 3.5, 1.0, 'Iris-versicolor'),
 (62, 5.9, 3.0, 4.2, 1.5, 'Iris-versicolor'),
 (65, 5.6, 2.9, 3.6, 1.3, 'Iris-versicolor'),
 (67, 5.6, 3.0, 4.5, 1.5, 'Iris-versicolor'),
 (68, 5.8, 2.7, 4.1, 1.0, 'Iris-versicolor'),
 (70, 5.6, 2.5, 3.9, 1.1, 'Iris-versicolor'),
 (71, 5.9, 3.2, 4.8, 1.8, 'Iris-versicolor'),
 (80, 5.7, 2.6, 3.5, 1.0, 'Iris-versicolor'),
 (81, 5.5, 2.4, 3.8, 1.1, 'Iris-versicolor'),
 (82, 5.5, 2.4, 3.7, 1.0, 'Iris-versicolor'),
 (83, 5.8, 2.7, 3.9, 1.2, 'Iris-versicolor'),
 (85, 5.4, 3.0, 4.5, 1.5, 'Iris-versicolor'),
 (89, 5.6, 3.0, 4.1, 1.3, 'Iris-versicolor'),
 (90, 5.5, 2.5, 4.0, 1.3, 'Iris-versicolor'),
 (91, 5.5, 2.6, 4.4, 1.2, 'Iris-versicolor'),
 (93, 5.8, 2.6, 4.0, 1.2, 'Iris-versicolor'),
 (94, 5.0, 2.3, 3.3, 1.0, 'Iris-versicolor'),
 (95, 5.6, 2.7, 4.2, 1.3, 'Iris-ve

In [33]:
query = """
    SELECT *
    from main_table_d
        where 
        class_name = 'Iris-versicolor' and 
        sepal_length_in_cm between 6 and 6.4
        and 
        sepal_width_in_cm between 2.5 and 3.3
"""
cursor.execute(query)
len(cursor.fetchall())

9

In [35]:
query = """
    SELECT *
    from main_table_d
        where 
        class_name = 'Iris-versicolor' and 
        sepal_length_in_cm between 6 and 6.4
        and 
        sepal_width_in_cm between 2.5 and 3.3
     and 
     (
     petal_width_in_cm = 1.3
     or
     petal_width_in_cm = 1.5
     or
     petal_width_in_cm = 1.6     
     )
"""
cursor.execute(query)
cursor.fetchall()

((73, 6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'),
 (79, 6.0, 2.9, 4.5, 1.5, 'Iris-versicolor'))

In [36]:
query = """
    SELECT *
    from main_table_d
        where 
        class_name = 'Iris-versicolor' and 
        sepal_length_in_cm between 6 and 6.4
        and 
        sepal_width_in_cm between 2.5 and 3.3
     and 
     (
     petal_width_in_cm in (1.3, 1.5, 1.6)    
     )
"""
cursor.execute(query)
cursor.fetchall()

((73, 6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'),
 (79, 6.0, 2.9, 4.5, 1.5, 'Iris-versicolor'))

In [37]:
query = """
    SELECT *
    from main_table_d
        where 
        class_name = 'Iris-versicolor' and 
        sepal_length_in_cm between 6 and 6.4
        and 
        sepal_width_in_cm between 2.5 and 3.3
     and 
     (
     petal_width_in_cm in (1.3, 1.5, 1.6)    
     )
     and id not in (79, 72, 98)
"""
cursor.execute(query)
cursor.fetchall()

((73, 6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'),)

In [38]:
query = """
    SELECT *
    from main_table_d
        where 
        class_name like '%ris-v%' and 
        sepal_length_in_cm between 6 and 6.4
        and 
        sepal_width_in_cm between 2.5 and 3.3
     and 
     (
     petal_width_in_cm in (1.3, 1.5, 1.6)    
     )
     and id not in (79, 72, 98)
"""
cursor.execute(query)
cursor.fetchall()

((73, 6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'),
 (134, 6.3, 2.8, 5.1, 1.5, 'Iris-virginica'))

In [39]:
import numpy as np

a = np.array([[10, np.NaN, np.Inf, 3], [8, 10, -3, 1], 
              [1000, 0.5, 12, np.NaN], [1, 1, np.NaN, 3], 
              [0, np.Inf, 3, 3], [-1, -1, np.Inf, 10]], float)


for i in range(a.shape[1]):
    column = a[:, i]
    count_nan = np.isnan(column).sum()
    count_inf = np.isinf(column).sum()
    print ('колонка {}: количество nan: {}, количество inf: {}'.format(i, count_nan, count_inf))
    
    
    
# В дополнение, отфильтровать все строки, в которых содержится хотя бы одно НЕ число)
condition = np.all(~np.isnan(a), axis=1) & np.all(~np.isinf(a), axis=1)
#print(condition)
print(a[condition])


колонка 0: количество nan: 0, количество inf: 0
колонка 1: количество nan: 1, количество inf: 1
колонка 2: количество nan: 1, количество inf: 2
колонка 3: количество nan: 1, количество inf: 0
[[ 8. 10. -3.  1.]]


In [40]:
a

array([[ 1.0e+01,      nan,      inf,  3.0e+00],
       [ 8.0e+00,  1.0e+01, -3.0e+00,  1.0e+00],
       [ 1.0e+03,  5.0e-01,  1.2e+01,      nan],
       [ 1.0e+00,  1.0e+00,      nan,  3.0e+00],
       [ 0.0e+00,      inf,  3.0e+00,  3.0e+00],
       [-1.0e+00, -1.0e+00,      inf,  1.0e+01]])

In [58]:
# С помощью встроенных в numpy средств отфильтровать соответствующие колонки 
#(где содержится хотя бы одно НЕ число).

x = a.transpose()
condition = np.all(~np.isnan(x), axis=1) & np.all(~np.isinf(x), axis=1)
print(x[condition])
#print(x[condition].transpose())

[[  10.    8. 1000.    1.    0.   -1.]]


In [44]:
a

array([[ 1.0e+01,      nan,      inf,  3.0e+00],
       [ 8.0e+00,  1.0e+01, -3.0e+00,  1.0e+00],
       [ 1.0e+03,  5.0e-01,  1.2e+01,      nan],
       [ 1.0e+00,  1.0e+00,      nan,  3.0e+00],
       [ 0.0e+00,      inf,  3.0e+00,  3.0e+00],
       [-1.0e+00, -1.0e+00,      inf,  1.0e+01]])

In [67]:
np.sum(np.isfinite(a), axis=1) >= 4

array([False,  True, False, False, False, False])

In [70]:
a.T[np.sum(np.isfinite(a), axis=0) >= 6]

array([[  10.,    8., 1000.,    1.,    0.,   -1.]])

In [71]:
query = """
    SELECT *
    from main_table_d
        where 
        class_name like '%ris-v%' and 
        sepal_length_in_cm between 6 and 6.4
        and 
        sepal_width_in_cm between 2.5 and 3.3
     and 
     (
     petal_width_in_cm in (1.3, 1.5, 1.6)    
     )
     order by sepal_length_in_cm desc
"""
cursor.execute(query)
cursor.fetchall()

((73, 6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'),
 (134, 6.3, 2.8, 5.1, 1.5, 'Iris-virginica'),
 (79, 6.0, 2.9, 4.5, 1.5, 'Iris-versicolor'))

In [72]:
query = """
    SELECT *
    from main_table_d
        where 
        class_name like '%ris-v%' and 
        sepal_length_in_cm between 6 and 6.4
        and 
        sepal_width_in_cm between 2.5 and 3.3
     and 
     (
     petal_width_in_cm in (1.3, 1.5, 1.6)    
     )
     order by sepal_length_in_cm desc, sepal_width_in_cm asc
     
"""
cursor.execute(query)
cursor.fetchall()

((73, 6.3, 2.5, 4.9, 1.5, 'Iris-versicolor'),
 (134, 6.3, 2.8, 5.1, 1.5, 'Iris-virginica'),
 (79, 6.0, 2.9, 4.5, 1.5, 'Iris-versicolor'))

In [75]:
query = """
    SELECT *
    from main_table_d
        where 
       
        sepal_length_in_cm between 6 and 6.4
        and 
        sepal_width_in_cm between 2.5 and 3.3
     
     order by sepal_length_in_cm desc, sepal_width_in_cm asc
     limit 4 offset 2
"""
cursor.execute(query)
cursor.fetchall()

# offset - смещение на 2 , то есть выводим со второй по шестую

((124, 6.3, 2.7, 4.9, 1.8, 'Iris-virginica'),
 (134, 6.3, 2.8, 5.1, 1.5, 'Iris-virginica'),
 (104, 6.3, 2.9, 5.6, 1.8, 'Iris-virginica'),
 (57, 6.3, 3.3, 4.7, 1.6, 'Iris-versicolor'))

In [78]:
query = """
    SELECT class_name,
    avg(sepal_length_in_cm),
    sum(sepal_length_in_cm),
    count(ID)
    from main_table_d
    group by class_name
        
"""
cursor.execute(query)
cursor.fetchall()

(('Iris-setosa', 5.006000003814697, 250.30000019073486, 50),
 ('Iris-versicolor', 5.935999975204468, 296.7999987602234, 50),
 ('Iris-virginica', 6.588000001907349, 329.40000009536743, 50))

In [81]:
query = """
    SELECT class_name,
    sum(sepal_length_in_cm) as sum_sepal_length
    from main_table_d
    group by class_name
        
"""


In [82]:
df = pd.read_sql(query, db_conn)
df

class_name  sum_sepal_length
0      Iris-setosa        250.300000
1  Iris-versicolor        296.799999
2   Iris-virginica        329.400000

In [94]:
query = """
    CREATE TABLE IF NOT EXISTS sort_decod_d(
    `ID` INT PRIMARY KEY,
    `NAME` TEXT
    )
        
"""
cursor.execute(query)
cursor.fetchall()

()

In [95]:
dct = {
    0: 'Iris-setosa',
    1: 'Iris-versicolor',
    2: 'Iris-virginica'
    }

query = """
INSERT INTO sort_decod_d VALUES (%s, %s)
"""

In [96]:
dct.items()

dict_items([(0, 'Iris-setosa'), (1, 'Iris-versicolor'), (2, 'Iris-virginica')])

In [97]:
cursor.executemany(query, dct.items())
db_conn.commit()

In [98]:
query = """
      select * from sort_decod_d
        """
cursor.execute(query)
cursor.fetchall()

((0, 'Iris-setosa'), (1, 'Iris-versicolor'), (2, 'Iris-virginica'))

In [99]:
query = """
      update main_table_d
      set class_name = %s
      where class_name = %s
        """


In [100]:
dct.items()

dict_items([(0, 'Iris-setosa'), (1, 'Iris-versicolor'), (2, 'Iris-virginica')])

In [101]:
cursor.executemany(query, dct.items())
db_conn.commit()

In [102]:
query_select_all 

'\nSELECT *\nfrom main_table_d\n'

In [103]:
cursor.execute(query_select_all)
cursor.fetchall()

((1, 5.1, 3.5, 1.4, 0.2, '0'),
 (2, 4.9, 3.0, 1.4, 0.2, '0'),
 (3, 4.7, 3.2, 1.3, 0.2, '0'),
 (4, 4.6, 3.1, 1.5, 0.2, '0'),
 (5, 5.0, 3.6, 1.4, 0.2, '0'),
 (6, 5.4, 3.9, 1.7, 0.4, '0'),
 (7, 4.6, 3.4, 1.4, 0.3, '0'),
 (8, 5.0, 3.4, 1.5, 0.2, '0'),
 (9, 4.4, 2.9, 1.4, 0.2, '0'),
 (10, 4.9, 3.1, 1.5, 0.1, '0'),
 (11, 5.4, 3.7, 1.5, 0.2, '0'),
 (12, 4.8, 3.4, 1.6, 0.2, '0'),
 (13, 4.8, 3.0, 1.4, 0.1, '0'),
 (14, 4.3, 3.0, 1.1, 0.1, '0'),
 (15, 5.8, 4.0, 1.2, 0.2, '0'),
 (16, 5.7, 4.4, 1.5, 0.4, '0'),
 (17, 5.4, 3.9, 1.3, 0.4, '0'),
 (18, 5.1, 3.5, 1.4, 0.3, '0'),
 (19, 5.7, 3.8, 1.7, 0.3, '0'),
 (20, 5.1, 3.8, 1.5, 0.3, '0'),
 (21, 5.4, 3.4, 1.7, 0.2, '0'),
 (22, 5.1, 3.7, 1.5, 0.4, '0'),
 (23, 4.6, 3.6, 1.0, 0.2, '0'),
 (24, 5.1, 3.3, 1.7, 0.5, '0'),
 (25, 4.8, 3.4, 1.9, 0.2, '0'),
 (26, 5.0, 3.0, 1.6, 0.2, '0'),
 (27, 5.0, 3.4, 1.6, 0.4, '0'),
 (28, 5.2, 3.5, 1.5, 0.2, '0'),
 (29, 5.2, 3.4, 1.4, 0.2, '0'),
 (30, 4.7, 3.2, 1.6, 0.2, '0'),
 (31, 4.8, 3.1, 1.6, 0.2, '0'),
 (32, 5.4, 3.4, 1

In [104]:
query = """
      select *
      from main_table_d
      join sort_decod_d 
      on main_table_d.class_name = sort_decod_d.ID
        """

cursor.execute(query)
cursor.fetchall()


((1, 5.1, 3.5, 1.4, 0.2, '0', 0, 'Iris-setosa'),
 (2, 4.9, 3.0, 1.4, 0.2, '0', 0, 'Iris-setosa'),
 (3, 4.7, 3.2, 1.3, 0.2, '0', 0, 'Iris-setosa'),
 (4, 4.6, 3.1, 1.5, 0.2, '0', 0, 'Iris-setosa'),
 (5, 5.0, 3.6, 1.4, 0.2, '0', 0, 'Iris-setosa'),
 (6, 5.4, 3.9, 1.7, 0.4, '0', 0, 'Iris-setosa'),
 (7, 4.6, 3.4, 1.4, 0.3, '0', 0, 'Iris-setosa'),
 (8, 5.0, 3.4, 1.5, 0.2, '0', 0, 'Iris-setosa'),
 (9, 4.4, 2.9, 1.4, 0.2, '0', 0, 'Iris-setosa'),
 (10, 4.9, 3.1, 1.5, 0.1, '0', 0, 'Iris-setosa'),
 (11, 5.4, 3.7, 1.5, 0.2, '0', 0, 'Iris-setosa'),
 (12, 4.8, 3.4, 1.6, 0.2, '0', 0, 'Iris-setosa'),
 (13, 4.8, 3.0, 1.4, 0.1, '0', 0, 'Iris-setosa'),
 (14, 4.3, 3.0, 1.1, 0.1, '0', 0, 'Iris-setosa'),
 (15, 5.8, 4.0, 1.2, 0.2, '0', 0, 'Iris-setosa'),
 (16, 5.7, 4.4, 1.5, 0.4, '0', 0, 'Iris-setosa'),
 (17, 5.4, 3.9, 1.3, 0.4, '0', 0, 'Iris-setosa'),
 (18, 5.1, 3.5, 1.4, 0.3, '0', 0, 'Iris-setosa'),
 (19, 5.7, 3.8, 1.7, 0.3, '0', 0, 'Iris-setosa'),
 (20, 5.1, 3.8, 1.5, 0.3, '0', 0, 'Iris-setosa'),
 (21, 5.4

In [105]:
query = """
      select *
      from main_table_d as t1
      join sort_decod_d as t2
      on t1.class_name = t2.ID
        """

cursor.execute(query)
cursor.fetchall()

((1, 5.1, 3.5, 1.4, 0.2, '0', 0, 'Iris-setosa'),
 (2, 4.9, 3.0, 1.4, 0.2, '0', 0, 'Iris-setosa'),
 (3, 4.7, 3.2, 1.3, 0.2, '0', 0, 'Iris-setosa'),
 (4, 4.6, 3.1, 1.5, 0.2, '0', 0, 'Iris-setosa'),
 (5, 5.0, 3.6, 1.4, 0.2, '0', 0, 'Iris-setosa'),
 (6, 5.4, 3.9, 1.7, 0.4, '0', 0, 'Iris-setosa'),
 (7, 4.6, 3.4, 1.4, 0.3, '0', 0, 'Iris-setosa'),
 (8, 5.0, 3.4, 1.5, 0.2, '0', 0, 'Iris-setosa'),
 (9, 4.4, 2.9, 1.4, 0.2, '0', 0, 'Iris-setosa'),
 (10, 4.9, 3.1, 1.5, 0.1, '0', 0, 'Iris-setosa'),
 (11, 5.4, 3.7, 1.5, 0.2, '0', 0, 'Iris-setosa'),
 (12, 4.8, 3.4, 1.6, 0.2, '0', 0, 'Iris-setosa'),
 (13, 4.8, 3.0, 1.4, 0.1, '0', 0, 'Iris-setosa'),
 (14, 4.3, 3.0, 1.1, 0.1, '0', 0, 'Iris-setosa'),
 (15, 5.8, 4.0, 1.2, 0.2, '0', 0, 'Iris-setosa'),
 (16, 5.7, 4.4, 1.5, 0.4, '0', 0, 'Iris-setosa'),
 (17, 5.4, 3.9, 1.3, 0.4, '0', 0, 'Iris-setosa'),
 (18, 5.1, 3.5, 1.4, 0.3, '0', 0, 'Iris-setosa'),
 (19, 5.7, 3.8, 1.7, 0.3, '0', 0, 'Iris-setosa'),
 (20, 5.1, 3.8, 1.5, 0.3, '0', 0, 'Iris-setosa'),
 (21, 5.4

In [ ]:
query = """
      select *
      from main_table_d as t1
      join sort_decod_d as t2
      on t1.class_name = t2.ID
        """

cursor.execute(query)
cursor.fetchall()

In [106]:
query = """
ALTER TABLE main_table_d
ADD NEW_COL INT
"""

cursor.execute(query)
cursor.fetchall()

()

In [107]:
cursor.execute(query_select_all)
cursor.fetchall()

((1, 5.1, 3.5, 1.4, 0.2, '0', None),
 (2, 4.9, 3.0, 1.4, 0.2, '0', None),
 (3, 4.7, 3.2, 1.3, 0.2, '0', None),
 (4, 4.6, 3.1, 1.5, 0.2, '0', None),
 (5, 5.0, 3.6, 1.4, 0.2, '0', None),
 (6, 5.4, 3.9, 1.7, 0.4, '0', None),
 (7, 4.6, 3.4, 1.4, 0.3, '0', None),
 (8, 5.0, 3.4, 1.5, 0.2, '0', None),
 (9, 4.4, 2.9, 1.4, 0.2, '0', None),
 (10, 4.9, 3.1, 1.5, 0.1, '0', None),
 (11, 5.4, 3.7, 1.5, 0.2, '0', None),
 (12, 4.8, 3.4, 1.6, 0.2, '0', None),
 (13, 4.8, 3.0, 1.4, 0.1, '0', None),
 (14, 4.3, 3.0, 1.1, 0.1, '0', None),
 (15, 5.8, 4.0, 1.2, 0.2, '0', None),
 (16, 5.7, 4.4, 1.5, 0.4, '0', None),
 (17, 5.4, 3.9, 1.3, 0.4, '0', None),
 (18, 5.1, 3.5, 1.4, 0.3, '0', None),
 (19, 5.7, 3.8, 1.7, 0.3, '0', None),
 (20, 5.1, 3.8, 1.5, 0.3, '0', None),
 (21, 5.4, 3.4, 1.7, 0.2, '0', None),
 (22, 5.1, 3.7, 1.5, 0.4, '0', None),
 (23, 4.6, 3.6, 1.0, 0.2, '0', None),
 (24, 5.1, 3.3, 1.7, 0.5, '0', None),
 (25, 4.8, 3.4, 1.9, 0.2, '0', None),
 (26, 5.0, 3.0, 1.6, 0.2, '0', None),
 (27, 5.0, 3.4, 1.6, 

In [108]:
query = """
      select *
      from main_table_d where new_col is null
        """

cursor.execute(query)
cursor.fetchall()

((1, 5.1, 3.5, 1.4, 0.2, '0', None),
 (2, 4.9, 3.0, 1.4, 0.2, '0', None),
 (3, 4.7, 3.2, 1.3, 0.2, '0', None),
 (4, 4.6, 3.1, 1.5, 0.2, '0', None),
 (5, 5.0, 3.6, 1.4, 0.2, '0', None),
 (6, 5.4, 3.9, 1.7, 0.4, '0', None),
 (7, 4.6, 3.4, 1.4, 0.3, '0', None),
 (8, 5.0, 3.4, 1.5, 0.2, '0', None),
 (9, 4.4, 2.9, 1.4, 0.2, '0', None),
 (10, 4.9, 3.1, 1.5, 0.1, '0', None),
 (11, 5.4, 3.7, 1.5, 0.2, '0', None),
 (12, 4.8, 3.4, 1.6, 0.2, '0', None),
 (13, 4.8, 3.0, 1.4, 0.1, '0', None),
 (14, 4.3, 3.0, 1.1, 0.1, '0', None),
 (15, 5.8, 4.0, 1.2, 0.2, '0', None),
 (16, 5.7, 4.4, 1.5, 0.4, '0', None),
 (17, 5.4, 3.9, 1.3, 0.4, '0', None),
 (18, 5.1, 3.5, 1.4, 0.3, '0', None),
 (19, 5.7, 3.8, 1.7, 0.3, '0', None),
 (20, 5.1, 3.8, 1.5, 0.3, '0', None),
 (21, 5.4, 3.4, 1.7, 0.2, '0', None),
 (22, 5.1, 3.7, 1.5, 0.4, '0', None),
 (23, 4.6, 3.6, 1.0, 0.2, '0', None),
 (24, 5.1, 3.3, 1.7, 0.5, '0', None),
 (25, 4.8, 3.4, 1.9, 0.2, '0', None),
 (26, 5.0, 3.0, 1.6, 0.2, '0', None),
 (27, 5.0, 3.4, 1.6, 

In [109]:
query = """
ALTER TABLE main_table_d
DROP COLUMN NEW_COL
"""

cursor.execute(query)
cursor.fetchall()

()

In [110]:
cursor.execute(query_select_all)
cursor.fetchall()

((1, 5.1, 3.5, 1.4, 0.2, '0'),
 (2, 4.9, 3.0, 1.4, 0.2, '0'),
 (3, 4.7, 3.2, 1.3, 0.2, '0'),
 (4, 4.6, 3.1, 1.5, 0.2, '0'),
 (5, 5.0, 3.6, 1.4, 0.2, '0'),
 (6, 5.4, 3.9, 1.7, 0.4, '0'),
 (7, 4.6, 3.4, 1.4, 0.3, '0'),
 (8, 5.0, 3.4, 1.5, 0.2, '0'),
 (9, 4.4, 2.9, 1.4, 0.2, '0'),
 (10, 4.9, 3.1, 1.5, 0.1, '0'),
 (11, 5.4, 3.7, 1.5, 0.2, '0'),
 (12, 4.8, 3.4, 1.6, 0.2, '0'),
 (13, 4.8, 3.0, 1.4, 0.1, '0'),
 (14, 4.3, 3.0, 1.1, 0.1, '0'),
 (15, 5.8, 4.0, 1.2, 0.2, '0'),
 (16, 5.7, 4.4, 1.5, 0.4, '0'),
 (17, 5.4, 3.9, 1.3, 0.4, '0'),
 (18, 5.1, 3.5, 1.4, 0.3, '0'),
 (19, 5.7, 3.8, 1.7, 0.3, '0'),
 (20, 5.1, 3.8, 1.5, 0.3, '0'),
 (21, 5.4, 3.4, 1.7, 0.2, '0'),
 (22, 5.1, 3.7, 1.5, 0.4, '0'),
 (23, 4.6, 3.6, 1.0, 0.2, '0'),
 (24, 5.1, 3.3, 1.7, 0.5, '0'),
 (25, 4.8, 3.4, 1.9, 0.2, '0'),
 (26, 5.0, 3.0, 1.6, 0.2, '0'),
 (27, 5.0, 3.4, 1.6, 0.4, '0'),
 (28, 5.2, 3.5, 1.5, 0.2, '0'),
 (29, 5.2, 3.4, 1.4, 0.2, '0'),
 (30, 4.7, 3.2, 1.6, 0.2, '0'),
 (31, 4.8, 3.1, 1.6, 0.2, '0'),
 (32, 5.4, 3.4, 1

In [111]:
query = """
ALTER TABLE main_table_d
MODIFY class_name INT
"""

cursor.execute(query)
cursor.fetchall()

()

In [112]:
cursor.execute(query_select_all)
cursor.fetchall()

((1, 5.1, 3.5, 1.4, 0.2, 0),
 (2, 4.9, 3.0, 1.4, 0.2, 0),
 (3, 4.7, 3.2, 1.3, 0.2, 0),
 (4, 4.6, 3.1, 1.5, 0.2, 0),
 (5, 5.0, 3.6, 1.4, 0.2, 0),
 (6, 5.4, 3.9, 1.7, 0.4, 0),
 (7, 4.6, 3.4, 1.4, 0.3, 0),
 (8, 5.0, 3.4, 1.5, 0.2, 0),
 (9, 4.4, 2.9, 1.4, 0.2, 0),
 (10, 4.9, 3.1, 1.5, 0.1, 0),
 (11, 5.4, 3.7, 1.5, 0.2, 0),
 (12, 4.8, 3.4, 1.6, 0.2, 0),
 (13, 4.8, 3.0, 1.4, 0.1, 0),
 (14, 4.3, 3.0, 1.1, 0.1, 0),
 (15, 5.8, 4.0, 1.2, 0.2, 0),
 (16, 5.7, 4.4, 1.5, 0.4, 0),
 (17, 5.4, 3.9, 1.3, 0.4, 0),
 (18, 5.1, 3.5, 1.4, 0.3, 0),
 (19, 5.7, 3.8, 1.7, 0.3, 0),
 (20, 5.1, 3.8, 1.5, 0.3, 0),
 (21, 5.4, 3.4, 1.7, 0.2, 0),
 (22, 5.1, 3.7, 1.5, 0.4, 0),
 (23, 4.6, 3.6, 1.0, 0.2, 0),
 (24, 5.1, 3.3, 1.7, 0.5, 0),
 (25, 4.8, 3.4, 1.9, 0.2, 0),
 (26, 5.0, 3.0, 1.6, 0.2, 0),
 (27, 5.0, 3.4, 1.6, 0.4, 0),
 (28, 5.2, 3.5, 1.5, 0.2, 0),
 (29, 5.2, 3.4, 1.4, 0.2, 0),
 (30, 4.7, 3.2, 1.6, 0.2, 0),
 (31, 4.8, 3.1, 1.6, 0.2, 0),
 (32, 5.4, 3.4, 1.5, 0.4, 0),
 (33, 5.2, 4.1, 1.5, 0.1, 0),
 (34, 5.5, 4.2, 1.4

In [113]:
query = """
DROP TABLE main_table_d
"""

cursor.execute(query)
cursor.fetchall()

()

In [114]:
cursor.execute(query_select_all)
cursor.fetchall()

ProgrammingError: (1146, "Table 'nordicDB.main_table_d' doesn't exist")

In [115]:
cursor.close()

In [116]:
db_conn.close()